import { v1 } from 'uuid'
import type { GeneralFormData } from '@/app/settings/components/GeneralInfo'

export function inputsArray(errors: any) {
  return [
    {
      id: v1(),
      errorText: 'Invalid name',
      title: 'First name',
      text: 'Tip',
      hasError: errors.name,
      placeholder: 'Bonnie',
      register: 'name' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid surname',
      title: 'Last name',
      text: 'Tip',
      hasError: errors.sername,
      placeholder: 'Green',
      register: 'sername' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid country',
      title: 'Country',
      text: 'Tip',
      hasError: errors.country,
      placeholder: 'United States',
      register: 'country' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid city',
      title: 'City',
      text: 'Tip',
      hasError: errors.city,
      placeholder: 'New York',
      register: 'city' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid address',
      title: 'Address',
      text: 'Tip',
      hasError: errors.address,
      placeholder: 'e.g. San Francisco',
      register: 'address' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid Education',
      title: 'Education',
      text: 'Tip',
      hasError: errors.education,
      placeholder: 'Education...',
      register: 'education' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid number',
      title: 'Phone number',
      text: 'Tip',
      hasError: errors.number,
      placeholder: 'e.g. 123 456 7890',
      register: 'number' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid birthday',
      title: 'Birthday',
      text: 'Tip',
      hasError: errors.birthday,
      placeholder: 'e.g. 01/01/2000',
      register: 'birthday' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid organization',
      title: 'Organization',
      text: 'Tip',
      hasError: errors.organization,
      placeholder: 'Company Name',
      register: 'organization' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid role',
      title: 'Role',
      text: 'Tip',
      hasError: errors.role,
      placeholder: 'React Developer',
      register: 'role' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid department',
      title: 'Department',
      text: 'Tip',
      hasError: errors.department,
      placeholder: 'Development',
      register: 'department' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid code',
      title: 'Code',
      text: 'Tip',
      hasError: errors.code,
      placeholder: 'e.g. 123456',
      register: 'code' as keyof GeneralFormData,
    },
  ]
}
