import { v1 } from 'uuid'
import type { GeneralFormData } from '@/app/settings/components/General'

export function inputsArray(errors: any) {
  return [
    {
      id: v1(),
      errorText: 'Invalid name',
      title: 'First name',
      text: 'Tip',
      hasError: errors.Name,
      placeholder: 'Bonnie',
      register: 'Name' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid surname',
      title: 'Last name',
      text: 'Tip',
      hasError: errors.Sername,
      placeholder: 'Green',
      register: 'Sername' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid country',
      title: 'Country',
      text: 'Tip',
      hasError: errors.Country,
      placeholder: 'United States',
      register: 'Country' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid city',
      title: 'City',
      text: 'Tip',
      hasError: errors.City,
      placeholder: 'New York',
      register: 'City' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid address',
      title: 'Address',
      text: 'Tip',
      hasError: errors.Address,
      placeholder: 'e.g. San Francisco',
      register: 'Address' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid email',
      title: 'Email',
      text: 'Tip',
      hasError: errors.Email,
      placeholder: 'example@company.com',
      register: 'Email' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid number',
      title: 'Number',
      text: 'Tip',
      hasError: errors.Number,
      placeholder: 'e.g. 123 456 7890',
      register: 'Number' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid birthday',
      title: 'Birthday',
      text: 'Tip',
      hasError: errors.Birthday,
      placeholder: 'e.g. 01/01/2000',
      register: 'Birthday' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid organization',
      title: 'Organization',
      text: 'Tip',
      hasError: errors.Organization,
      placeholder: 'Company Name',
      register: 'Organization' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid role',
      title: 'Role',
      text: 'Tip',
      hasError: errors.Role,
      placeholder: 'React Developer',
      register: 'Role' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid department',
      title: 'Department',
      text: 'Tip',
      hasError: errors.Department,
      placeholder: 'Development',
      register: 'Department' as keyof GeneralFormData,
    },
    {
      id: v1(),
      errorText: 'Invalid code',
      title: 'Code',
      text: 'Tip',
      hasError: errors.Code,
      placeholder: 'e.g. 123456',
      register: 'Code' as keyof GeneralFormData,
    },
  ]
}
