export const skillsOptions = [
  { label: crypto.randomUUID(), value: 'JavaScript' },
  { label: crypto.randomUUID(), value: 'TypeScript' },
  { label: crypto.randomUUID(), value: 'React' },
  { label: crypto.randomUUID(), value: 'Node.js' },
  { label: crypto.randomUUID(), value: 'HTML/CSS' },
  { label: crypto.randomUUID(), value: 'GraphQL' },
  { label: crypto.randomUUID(), value: 'Next.js' },
  { label: crypto.randomUUID(), value: 'Vue.js' },
  { label: crypto.randomUUID(), value: 'Tailwind CSS' },
  { label: crypto.randomUUID(), value: 'Figma' },
  { label: crypto.randomUUID(), value: 'Docker' },
  { label: crypto.randomUUID(), value: 'Kubernetes' },
  { label: crypto.randomUUID(), value: 'Git' },
  { label: crypto.randomUUID(), value: 'Firebase' },
  { label: crypto.randomUUID(), value: 'Supabase' },
  { label: crypto.randomUUID(), value: 'AWS' },
  { label: crypto.randomUUID(), value: 'Python' },
  { label: crypto.randomUUID(), value: 'Java' },
  { label: crypto.randomUUID(), value: 'C++' },
  { label: crypto.randomUUID(), value: 'Jest' },
]

export const hobbiesOptions = [
  { label: crypto.randomUUID(), value: 'Coding challenges' },
  { label: crypto.randomUUID(), value: 'Open source contribution' },
  { label: crypto.randomUUID(), value: 'Reading tech blogs' },
  { label: crypto.randomUUID(), value: 'Playing chess' },
  { label: crypto.randomUUID(), value: 'Photography' },
  { label: crypto.randomUUID(), value: 'Traveling' },
  { label: crypto.randomUUID(), value: 'Music production' },
  { label: crypto.randomUUID(), value: 'Gaming' },
  { label: crypto.randomUUID(), value: 'Playing guitar' },
  { label: crypto.randomUUID(), value: 'Running' },
  { label: crypto.randomUUID(), value: 'Cycling' },
  { label: crypto.randomUUID(), value: 'Cooking' },
  { label: crypto.randomUUID(), value: 'Woodworking' },
  { label: crypto.randomUUID(), value: 'Watching documentaries' },
  { label: crypto.randomUUID(), value: 'Blogging' },
  { label: crypto.randomUUID(), value: 'Learning new languages' },
  { label: crypto.randomUUID(), value: 'Meditation' },
  { label: crypto.randomUUID(), value: 'Board games' },
  { label: crypto.randomUUID(), value: 'Gardening' },
  { label: crypto.randomUUID(), value: 'Fitness' },
]
